# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-01 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItem',
            new_name='TodoItems',
        ),
    ]
